# Generated by Django 6.0.3 on 2026-03-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='gift_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='gift_cards/events/'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_method',
            field=models.CharField(choices=[('gift_card', 'Gift Card'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
