# Generated by Django 6.0.3 on 2026-03-06 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebs', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='celebrity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='celebs.celebrity'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='memberships.membershiptier'),
        ),
    ]
