# Generated by Django 6.0.3 on 2026-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('acting', 'Acting'), ('comedy', 'Comedy'), ('politics', 'Politics'), ('business', 'Business'), ('other', 'Other')], default='other', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='celebs/photos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='celebs/covers/')),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
